src/AdminLTE.Web/Controllers/CierreCajaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CapaEntidades;

namespace AdminLTE.Web.Controllers
{
    public class CierreCajaController : Controller
    {
        CapaNegocio.CierreCaja_CN Caja = new CapaNegocio.CierreCaja_CN();
        CapaDatos.Conexion funcion = new CapaDatos.Conexion();
        // GET: CierreCaja
        public ActionResult Index()
        {
            if (funcion.Verificar())
            {
                int idalmacen = Convert.ToInt32(Session["idalmacen"].ToString());
                //ViewBag.ListaCajero = Caja.ObtenerCajero(idalmacen);
                return View("~/Views/CierreCaja.cshtml");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult ObtenerDetalleCaja()
        {
            string usuario = Session["usuario"].ToString();
            int idalmacen = Convert.ToInt32(Session["idalmacen"].ToString());
            return Json(Caja.ObtenerDetalleCierre(idalmacen, usuario));
        }

        public JsonResult GuardarCierre(List<CierreDia> DatoCierre)
        {
            int codCidi = Caja.GuardarCierre(DatoCierre);
            return new JsonResult { Data = new { dato = codCidi } };
        }

        public JsonResult ValidarInicioCaja(string usuario, int CodAlmacen)
        {
            bool Estado = Caja.InicioDia(usuario, CodAlmacen);
            return new JsonResult { Data = new { dato = Estado } };
        }

        public ActionResult InicioDia()
        {
            if (funcion.Verificar())
            {                     
                return View("~/Views/InicioDia.cshtml");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
        }

        public JsonResult ObtenerDatoInicioDia()
        {
            string usuario = Session["usuario"].ToString();
            int idalmacen = Convert.ToInt32(Session["idalmacen"].ToString());

            return Json(Caja.DatoInicioDia(usuario, idalmacen));

        }

        public JsonResult GuardarInicioDia(double monto, int codIndi)
        {            
            return new JsonResult { Data = new { dato = Caja.guardarInicioDia(monto,codIndi) } };
        }

    }
}

src/AdminLTE.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdminLTE.Web.Controllers
{
    public class LoginController : Controller
    {
        CapaNegocio.Producto_cn producto = new CapaNegocio.Producto_cn();
        
        // GET: Login
        public ActionResult Index()
        {
            Session["usuario"] = null;
            ViewBag.ListaAlmacen = producto.ObtenerAlmacen();
            return View("~/Views/Login.cshtml");
        }

        public JsonResult IniciarLogin(string usuario, string password, string idalmacen, string NombreAlmacen)
        {
            Session["idalmacen"] = idalmacen;
            Session["usuario"] = usuario;
            Session["nombreUsuario"] = producto.ObtenerNombre(usuario);
            Session["NombreAlmacen"] = NombreAlmacen;
            Session["CodUsuario"] = producto.ObtenerCodUsuario(usuario);
            Session["PinUsuario"] = producto.ObtenerPinUsuario(usuario);

            return (new JsonResult { Data = new { data = producto.VerificarUsuario(usuario, password) } });
        }

        public JsonResult verificar()
        {
            bool obj;
            if (System.Web.HttpContext.Current.Session["usuario"] == null){

                obj = false;
            }
            else{
                obj = true;
            }
            return (new JsonResult { Data = new { data = obj } });

        }

        public JsonResult ObtenerAlmacenUsuario(string usuario)
        {
            return Json(producto.ObtenerAlmacenUsuario(usuario));
        }

        public JsonResult VerificarRolUsuario()
        {
            string Usuario = Session["usuario"].ToString();
            bool estado = producto.ObtenerRolUsuario(Usuario);
            return new JsonResult { Data = new { dato = estado } };
        }

    }
}

src/AdminLTE.Web/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using Newtonsoft.Json;
using CapaEntidades;
using QRCoder;
using System.Drawing;


using Microsoft.Reporting.WebForms;
using System.Data;
using System.IO;
using System.Data.SqlClient;
using System.Configuration;
using System.Drawing.Printing;
using System.Drawing.Imaging;

namespace AdminLTE.Web.Controllers
{
    public class VentaController : Controller
    {
        CapaDatos.Conexion funcion = new CapaDatos.Conexion();
        CapaNegocio.Producto_cn Producto = new CapaNegocio.Producto_cn();

        CapaNegocio.Venta_BL Venta = new CapaNegocio.Venta_BL();
        CapaEntidades.Venta VentaEntidad = new CapaEntidades.Venta();
        CapaNegocio.DetalleMesa_CN DetalleMesa = new CapaNegocio.DetalleMesa_CN();

        // GET: Venta
        public ActionResult Index(int m, int c)
        {
            if (funcion.Verificar())
            {
                //ViewBag.ListaCliente = Producto.ObtenerCliente();
                //ViewBag.ListaBanco = Venta.ObtenerBanco();
                //ViewBag.ListaEmpresaDelivery = Venta.ObtenerEmpresaDelivery();
                //ViewBag.ListaTipoTarjeta = Venta.ObtenerTipoTarjeta();
                //ViewBag.TipoDocumentoFact = Venta.ObtenerTipoDocumentoFac();
              
                if (c>0)
                {
                    m = 0;
                }
                ViewBag.tc = Venta.Tc();
                ViewBag.EstadoFact = Venta.EstadoFacturacion(Convert.ToInt32(Session["idalmacen"].ToString()));

                ViewBag.CodVenta = Venta.ObtenerCodVenta(m,c);  //id
                ViewBag.CodMesa = m;
                ViewBag.DescripcionMesa = Venta.DescripcionMesa(m);
                ViewBag.DescripcionCuenta = Venta.DescripcionCuenta(c);
                ViewBag.codCuenta = c;
                ViewBag.UsoCodigoUsuario = DetalleMesa.UsoCodigoUsuario();
                ViewBag.ListaClasificacion = Producto.ObtenerClasificacion(1);
                return View("~/Views/Pedido.cshtml");
            }
            else
            {
                return RedirectToAction("Index", "Login");
            }
          
        }

        public ActionResult Verificar()
        {
            ViewBag.Estado = 1;
            return View("~/Views/Inicio.cshtml");
        }

        public JsonResult VerificarStock(int codProd, int codAlmacen)
        {
            double Stock = Venta.VerificarStock(codProd, codAlmacen);
            return (new JsonResult { Data = new { data = Stock } });
        }
        public JsonResult ObtenerProducto(string producto)
        {
            string productos = Venta.ObtenerProducto(producto);
            return new JsonResult { Data = new { dato = productos } };
        }

        public JsonResult GuardarVenta(List<Venta> DatoVenta, List<DetalleVenta> DetalleVenta, List<DetalleComposicion> DetalleComposicion, List<ProductoEliminado> ProductoEliminado)
        {
            //string dato = Request.Form.Get("Venta");
            //VentaEntidad = JsonConvert.DeserializeObject<Venta>(dato);

           int codVent = Venta.GuardarVenta(DatoVenta, DetalleVenta, DetalleComposicion, ProductoEliminado);
            return new JsonResult { Data = new { dato = codVent } };
        }

        public JsonResult DatosCliente(int nroDocu)
        {
            return Json(Venta.ObtenerDatosDocumento(nroDocu));
        }

        public JsonResult VerificarProductoHomologado(int CodProducto)
        {
           int estado = Venta.VerificarProdHomologado(CodProducto);
            return new JsonResult { Data = new { dato = estado} };
        }


        [HttpPost]
        public ActionResult Qr1()
        {
            QRCodeGenerator qr = new QRCodeGenerator();
            QRCodeData qrCodeData = qr.CreateQrCode("system", QRCodeGenerator.ECCLevel.Q);
            QRCode qrCode = new QRCode(qrCodeData);
            Bitmap qrCodeImage = qrCode.GetGraphic(20);
            ImageConverter convert = new ImageConverter();
            byte[] qrbyte = (byte[])convert.ConvertTo(qrCodeImage, typeof(byte[]));
            ViewBag.url = "data:image/png;base64," + Convert.ToBase64String(qrbyte);
            return View("~/Views/VentaRapida.cshtml");
            //return View("~/Views/VentaRapida.cshtml", qrbyte);


            //PngByteQRCode qrCode = new PngByteQRCode(qrCodeData);
            //byte[] qrCodeImage = qrCode.GetGraphic(20);
            //string model = Convert.ToBase64String(qrCodeImage);
            //return View("~/Views/VentaRapida.cshtml", model);

        }

        public ActionResult ReporteNotaVenta(int codventa)
        {
            string EstadoObser = "";
            int codAlma = Convert.ToInt32(Session["idalmacen"].ToString());
            string ubicacionImpr = Venta.UbicacionImpresora(codAlma);

            string id = "Pdf";
            LocalReport lr = new LocalReport();
            string path = "";
            DataSet ds = new DataSet();
            DataSet dsAbono = new DataSet();

            path = Path.Combine(Server.MapPath("~/Informe"), "RptNotaVenta.rdlc");
            lr.ReportPath = path;

            ds = VentaDetalle(codventa);
            lr.DataSources.Add(new ReportDataSource("DataSet1", ds.Tables["tbventa"]));

            dsAbono = AbonoDetalle(codventa);
            lr.DataSources.Add(new ReportDataSource("DataSet2", dsAbono.Tables["tbabono"]));

            ds = Totales(codventa);
            lr.DataSources.Add(new ReportDataSource("DataSet3", ds.Tables["tbtotal"]));            

            //ReportParameter[] reportParameters = new ReportParameter[1];  Parametros
            //reportParameters[0] = new ReportParameter("TotalGeneral", "25", false);
            //lr.SetParameters(reportParameters);

            string reportType = id;
            string mimeType;
            string encoding;
            string fileNameExtension;
            string deviceInfo = @"<DeviceInfo>
                    <OutputFormat>EMF</OutputFormat>
                    <EmbedFonts>None</EmbedFonts>
                   </DeviceInfo>";
            //"<DeviceInfo>" +         
            //" <OutputFormat>" + id + "</OutputFormat>" +
            //" <PageWidth>8.5in</PageWidth>" +
            //" <PageHeight>11in</PageHeight>" +
            //" <MarginTop>0in</MarginTop>" +
            //" <MarginLeft>0in</MarginLeft>" +
            //" <MarginRight>0in</MarginRight>" +
            //" <MarginBottom>0.0in</MarginBottom>" +
            //"</DeviceInfo>";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes = lr.Render(
            reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

            ////Imprimir////

            Warning[] warnings2;
            string[] streamIds;
            string mimeType2 = string.Empty;
            string encoding2 = string.Empty;
            string extension2 = string.Empty;
          
            try
            {
                byte[] bytes = lr.Render("Image", deviceInfo, out mimeType2, out encoding2, out extension2, out streamIds, out warnings2);
                using (MemoryStream ms = new MemoryStream(bytes))
                {
                    using (PrintDocument printDoc = new PrintDocument())
                    {
                        printDoc.PrinterSettings.PrinterName = ubicacionImpr;
                        printDoc.PrintPage += (s, e) =>
                        {
                            Metafile pageImage = new Metafile(ms);
                            e.Graphics.DrawImage(pageImage, e.PageBounds);
                        };
                        printDoc.Print(); 
                    }
                }
                ReporteComanda(codventa);
            }
            catch (Exception e)
            {
                EstadoObser = "Impresora no válida";
            }


            return new JsonResult { Data = new { dato = EstadoObser } };
            //return File(renderedBytes, mimeType);

            //var deviceInfo = @"<DeviceInfo>
            //        <EmbedFonts>None</EmbedFonts>
            //       </DeviceInfo>";
            //byte[] bytes = rdlc.Render("PDF", deviceInfo);d
        }


        public void ReporteComanda(int codventa)
        {
            int codAlma = Convert.ToInt32(Session["idalmacen"].ToString());
            string ubicacionImpr = Venta.UbicacionImpresora(codAlma);

            string id = "Pdf";
            LocalReport lr = new LocalReport();
            string path = "";
            DataSet ds = new DataSet();
            DataSet dsDetalleComp = new DataSet();

            path = Path.Combine(Server.MapPath("~/Informe"), "RptComanda.rdlc");
            lr.ReportPath = path;

            ds = VentaDetalle(codventa);
            lr.DataSources.Add(new ReportDataSource("DataSet1", ds.Tables["tbventa"]));

            dsDetalleComp = DsDetalleComposicion(codventa);
            lr.DataSources.Add(new ReportDataSource("DataSet2", dsDetalleComp.Tables["tbComposicion"]));

            string reportType = id;
            string mimeType;
            string encoding;
            string fileNameExtension;
            string deviceInfo = @"<DeviceInfo>
                    <OutputFormat>EMF</OutputFormat>
                    <EmbedFonts>None</EmbedFonts>
                   </DeviceInfo>";
            Warning[] warnings;
            string[] streams;
            byte[] renderedBytes = lr.Render(
            reportType, deviceInfo, out mimeType, out encoding, out fileNameExtension, out streams, out warnings);

            ////Imprimir////

            Warning[] warnings2;
            string[] streamIds;
            string mimeType2 = string.Empty;
            string encoding2 = string.Empty;
            string extension2 = string.Empty;

            try
            {

src/AdminLTE.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="google" content="notranslate" />
    <title>XpertoRest</title>
    <script>
         var baseURL = '@Url.Content("~/")';
    </script>
    @Styles.Render("~/Content/css")

    @RenderSection("Styles", required: false)

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/lib")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/customs")
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/datatables.net-bs4@1.13.6/css/dataTables.bootstrap4.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.4.2/sweetalert2.min.css" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />

</head>
<body class="hold-transition">
    <div class="wrapper">
        @Html.Partial("_NavBar")
        @*@Html.Partial("_SideBar")*@
        <div class="content-wrapper">
            @*content-wrapper*@

            @RenderBody()
        </div>

        @*<footer class="main-footer">
                <strong>Copyright &copy; 2014-2019 <a href="http://adminlte.io">AdminLTE.io</a>.</strong>
                All rights reserved.
                <div class="float-right d-none d-sm-inline-block">
                    <b>Version</b> 3.0.2
                </div>
            </footer>*@

        @*<footer class="main-footer">
                <strong>Copyright &copy; 2024 XPERTO</strong>
            </footer>*@


        <!-- Control Sidebar -->
        <aside id="control_sidebar" class="control-sidebar alinear2" style="width: 370px; box-shadow: 0 0 30px #272424; background:#ffffff">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <br />
                <h5 style="font-weight:bold">Orden de pedido</h5>
                <p id="mesaNro1"></p>


                <div class="form-group">
                    <div class="input-group input-group-sm">
                        <div class="input-group-append">
                            <span class="input-group-text" style="font-weight:bold">Cliente:</span>
                        </div>
                        <input type="text" class="form-control" id="nombCliente1" value="CLIENTES VARIOS" disabled>
                    </div>
                </div>

                <div class="form-group alinear2">
                    <table id="tbproducto11" class="table table-condensed table-hover table-sm" style="width:100%">
                        <colgroup>
                            @*<col style="width: 25%" />
                                <col style="width: 50%" />
                                <col style="width: 20%" />
                                <col style="width: 20%" />
                                <col style="width: 20%" />
                                <col style="width: 20%" />
                                <col style="width: 20%" />
                                <col style="width: 20%" />*@

                            <col style="width: 5%" />
                            <col style="width: 30%" />
                            <col style="width: 30%" />
                            <col style="width: 10%" />
                            <col style="width: 10%" />
                            <col style="width: 10%" />
                            <col style="width: 5%" />                       

                        </colgroup>
                        <thead>
                            <tr style="font-weight:bold">
                                <td>N°</td>
                                <td>Producto</td>
                                <td>Observación</td>
                                <td>Cantidad</td>
                                <td>Precio</td>
                                <td>SubTotal</td>
                                <td>Codprod</td>
                                <td></td>
                                <td></td>
                                <td>TipClas</td>
                                <td>TipUnid</td>
                                <td>Nuevo</td>
                                <td>CodDecv</td>
                                <td>IdObserv</td>
                                <td>CodUsuDetalle</td>
                            </tr>
                        </thead>
                        <tbody style="font-size: 12px">
                        </tbody>
                    </table>

                </div>
                <label id="lblTotal1"></label>

                <div class="form-group alinear2">

                    <table id="tbcomposicion111" class="table table-condensed table-hover table-striped table-sm" style="width:100%">
                        <colgroup>
                            <col style="width: 25%" />
                            <col style="width: 50%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                            <col style="width: 20%" />
                        </colgroup>
                        <thead>
                            <tr style="font-weight:bold">
                                <td>N°</td>
                                <td>Producto</td>
                                <td>Tipo</td>
                                <td>Detalle</td>
                                <td>Cant</td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td>pLlevar</td>
                                <td>porc</td>
                                <td>precio</td>
                                <td>CantProdPrinc</td>
                                <td>PrecGeneral</td>
                                <td>tipClas</td>
                                <td>num</td>
                                <td>Nuevo</td>
                                <td>NC</td>
                            </tr>
                        </thead>
                        <tbody style="font-size: 12px">
                        </tbody>
                    </table>

                </div>
                <button type="button" class="btn btn-success btn-sm" style="border-color:cyan; background:#193d52" onclick="ConfirmacionVenta()"><i class="fa-regular fa-floppy-disk"></i>  Guardar</button>
                <button type="button" class="btn btn-danger btn-sm" style="border-color: cyan; background: #193d52" onclick="CancelarPedido()"> <i class="fa-solid fa-xmark"></i> Cancelar</button>
                <button type="button" class="btn btn-warning btn-sm" style="border-color:cyan" id="btnPrecuenta" onclick="ImprimirPrecuenta()"><i class="fa-solid fa-print"></i> Precuenta</button>
            </div>
        </aside>
        <!-- /.control-sidebar -->
    </div>
    @Scripts.Render("~/bundles/scripts")
    @RenderSection("scripts", required: false)


    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.4.2/sweetalert2.min.js"></script>
</body>
</html>


<script>
    $('[data-widget="pushmenu"]').PushMenu("collapse")
</script>

<style type="text/css">
    .alinear2 {
        /*   height: auto;*/
        overflow-y: scroll;
    }
</style>

src/AdminLTE.Web/Views/Shared/_SideBar.cshtml
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4" style="background:#088078">
    <!-- Brand Logo -->
    <a class="brand-link" style="text-align: center; background: #088078">
        @*<img src="~/Content/Images/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
        style="opacity: .8">*@
        @*<span class="brand-text font-weight-bold" style="font-family:Century">XPERTO</span>*@
        <img src="~/Content/Images/Xperto.png" class="img-fluid">
    </a>

    <!-- Sidebar -->
    <div class="sidebar" hidden>
        <!-- Sidebar user panel (optional) -->

        @*<div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Content/Images/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">Christian Irvin</a>
            </div>
        </div>*@

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview ">
                    @*menu-open*@
                    <a href="#" class="nav-link active">
                        <i class="nav-icon far fa-list-alt"></i>
                        <p>
                            OPCION VENTA
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Verificar", "Venta")" class="nav-link active">
                                <i class="fas fa-angle-down nav-icon"></i>
                                <p>Venta Rapida</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("InicioDia", "CierreCaja")" class="nav-link active">
                                <i class="fas fa-angle-down nav-icon"></i>
                                <p>Inicio día</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "CierreCaja")" class="nav-link active">
                                <i class="fas fa-angle-down nav-icon"></i>
                                <p>Cierre Caja</p>
                            </a>
                        </li>
                    </ul>

                </li>
                @*<li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Simple Link
                            <span class="right badge badge-danger">New</span>
                        </p>
                    </a>
                </li>*@
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>